# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=30)),
                ('gimg', models.ImageField(upload_to='df_goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gunit', models.CharField(default='500g', max_length=20)),
                ('gsort', models.IntegerField(default=0)),
                ('gdescribe', models.CharField(max_length=200)),
                ('gstock', models.IntegerField()),
                ('gclick', models.IntegerField()),
            ],
            options={
                'db_table': 'df_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'df_type',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsType'),
        ),
    ]
