# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20180610_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='df_goods', verbose_name='轮播图片')),
                ('name', models.CharField(max_length=20, verbose_name='轮播商品名称')),
                ('trackid', models.CharField(max_length=16, verbose_name='通用ID')),
            ],
        ),
    ]
